# 矩陣基本運算

使用numpy套件的array，輸入矩陣a

$a=\begin{bmatrix}
1 & 2 & 3 \\
3 & 4 & 5
\end{bmatrix}
$

$
b=\begin{pmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{pmatrix}
$

In [0]:
import numpy as np

a = np.array([[1, 2, 3],
              [3, 4, 5]])
print(a)

b=np.array([2,3,5],
           [4,5,6])

[[1 2 3]
 [3 4 5]]


輸入矩陣b，並且使用b矩陣shape屬性，查詢其矩陣大小

$b=\begin{bmatrix}
2 & 1 & 3 \\
4 & 2 & 5
\end{bmatrix}
$



In [0]:
b=np.array([[2, 1, 3],
            [4, 2, 5]])
print(b)
print(b.shape)

[[2 1 3]
 [4 2 5]]
(2, 3)


## 轉置矩陣

使用b.T語法，求得b矩陣的轉置矩陣，存入c矩陣

$c=b'=\begin{bmatrix}
2 & 4 \\
1 & 2 \\
3 & 5
\end{bmatrix}
$

In [0]:
c = b.T
print(c)

[[2 4]
 [1 2]
 [3 5]]


## 矩陣加/減法
$d=a+b=
\begin{bmatrix}
1 & 2 & 3 \\
3 & 4 & 5
\end{bmatrix}+
\begin{bmatrix}
2 & 1 & 3 \\
4 & 2 & 5
\end{bmatrix}
=\begin{bmatrix}
3 & 3 & 6 \\
7 & 6 & 10
\end{bmatrix}
$

$
\begin{bmatrix}
1 & 2 & 3 \\
3 & 4 & 5
\end{bmatrix}-
\begin{bmatrix}
2 & 1 & 3 \\
4 & 2 & 5
\end{bmatrix}
=\begin{bmatrix}
-1 & 1 & 0 \\
-1 & 2 & 0
\end{bmatrix}
$

In [0]:
print('a+b')
d=a+b
print(d)

print('a-b')
print(a-b)

a+b
[[ 3  3  6]
 [ 7  6 10]]
a-b
[[-1  1  0]
 [-1  2  0]]


## 矩陣乘法(scalar product)
每一個矩陣元素相乘

$e=a*b=
\begin{bmatrix}
1 & 2 & 3 \\
3 & 4 & 5
\end{bmatrix} *
\begin{bmatrix}
2 & 1 & 3 \\
4 & 2 & 5
\end{bmatrix}
=\begin{bmatrix}
2 & 2 & 9 \\
12 & 8 & 25
\end{bmatrix}
$


In [0]:
e=a*b
print('a*b=')
print(e)

a*b=
[[ 2  2  9]
 [12  8 25]]


## 矩陣內積(dot product)
矩陣乘法

$e=a \times c=
\begin{bmatrix}
1 & 2 & 3 \\
3 & 4 & 5
\end{bmatrix} \times
\begin{bmatrix}
2 & 4 \\
1 & 2 \\
3 & 5 
\end{bmatrix}
=\begin{bmatrix}
13 & 23 \\
25 & 45
\end{bmatrix}
$


In [0]:
g=np.dot(a,c)
print(g)

[[13 23]
 [25 45]]


In [0]:
from numpy.linalg import inv

Q=np.dot(a,a.T)
print('A*At')
print(Q)

N=inv(Q)
print('inv(A*At)')
print(N)

A*At
[[14 26]
 [26 50]]
inv(A*At)
[[ 2.08333333 -1.08333333]
 [-1.08333333  0.58333333]]


$
A = \begin{bmatrix} 
    a_{11} & a_{12} & \dots \\
    \vdots & \ddots & \\
    a_{k1} &        & a_{kk} 
    \end{bmatrix}
$