# Level Net
## 間接觀測平差
所謂間接觀測(Indirect Observation)，是指測量結果(未知參數)並非直接測定，而是經由兩個或兩個以上的觀測量依其相應的函數關係間接計算而得者，例如極坐標法的平面位置定位，是由觀測的距離與方位角，再經由三角函數計算得到。

將每一個觀測量都建立成未知數的函數，並在多餘觀測的基礎上，由觀測量建構觀測方程式，利用最小二乘法對未知參數進行最或是值解的統計推估(平差求解)，同時由平差後改正數進行精度(誤差)分析，以暸解觀測與成果之品質。



## Python 最小二乘法模組
<hr>

### 輸入參數：
* A:      設計矩陣
* L:      觀測矩陣
* p:      賦予權值向量   (選項)
* px:     未知數加權矩陣 (選項)
* unit:   未知數單位表示 (選項)

<hr>

### 輸出參數
* X:      未知數
* V:      誤差矩陣
* sigma0: 單位權標準誤差
* DX:     未知數精度矩陣
* sL:     未知數標準誤差
* P:      加權矩陣

<hr>
* 嘉南藥理大學測量製圖學分班

* 作者：  M.J. Huang
* email: geodesy.cnu@gmail.com

<hr>



# 直接水準平差範例
<img src="https://drive.google.com/uc?id=14hJ1Z9pltYwGYfu78ZspdBt2F_dVcBHi">
<img src="https://drive.google.com/uc?id=1TUDLP-adH8fj8gCHIh4o4HQqfedosDKf">

In [1]:
# 匯入最小二乘平差法套件
from pygeodadj.LSEA import LESA
from pygeodadj.LSEA import LESA_Print

import numpy as np

A=np.array([
   [1,   0,   0],
   [-1,  0,   0],
   [0,   0,   1],
   [0,   0,  -1],
   [-1,  1,   0],
   [0,   1,   0],
   [0,  -1,   1]
])

L=np.array([
    105.1,
   -105.16,
    106.25,
   -106.13,
     -0.68,
    104.5,
      1.7
])
L=L.T
# 無加權矩陣
X, V, sigma0, DX, sL, P, N, U=LESA(A,L,unit='m')
LESA_Print(A,L, X, V, sigma0, DX, sL, P, N, U)

***** 最小二乘法計算模組報表 *****

設計矩陣A
[[ 1  0  0]
 [-1  0  0]
 [ 0  0  1]
 [ 0  0 -1]
 [-1  1  0]
 [ 0  1  0]
 [ 0 -1  1]]

觀測矩陣L
  105.1000
 -105.1600
  106.2500
 -106.1300
   -0.6800
  104.5000
    1.7000

加權矩陣P
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]

法方程式 N矩陣
[[ 3. -1.  0.]
 [-1.  3. -1.]
 [ 0. -1.  3.]]

法方程式 U矩陣
  210.9400
  102.1200
  214.0800

未知數X
  105.1410
  104.4829
  106.1876

誤差矩陣V
    0.0410
    0.0190
   -0.0624
   -0.0576
    0.0219
   -0.0171
    0.0048

單位權標準誤差：+/- 0.0501

未知數及精度分析
105.1410m +/- 0.0309 (m)
104.4829m +/- 0.0328 (m)
106.1876m +/- 0.0309 (m)

觀測量精度矩陣
    0.0309
    0.0309
    0.0309
    0.0309
    0.0363
    0.0328
    0.0363


<img src="https://drive.google.com/uc?id=10-LDIQBmsTNrH_0T3LR4sf4HtzPRXBPN">

# 直接水準平差範例
<img src="https://drive.google.com/uc?id=11PpwvtQ6LHz3fosO9hd6JroLIkrCJMMR">

In [2]:
# 指定加權矩陣的使用方法
A=np.array([
   [1,   0,   0],
   [-1,  1,   0],
   [0,  -1,   0],
   [0,   0,  -1],
   [-1,  0,   1],
   [0,  -1,   1]
])

L=np.array([
    25.021,
     5.012,
   -29.981,
   -40.020,
    14.990,
    10.014
])
L=L.T

w=np.array([3,2,2,3,3,6])
X, V, sigma0, DX, sL, P, N, U=LESA(A,L,p=w,unit='m')
LESA_Print(A,L, X, V, sigma0, DX, sL, P, N, U)

***** 最小二乘法計算模組報表 *****

設計矩陣A
[[ 1  0  0]
 [-1  1  0]
 [ 0 -1  0]
 [ 0  0 -1]
 [-1  0  1]
 [ 0 -1  1]]

觀測矩陣L
   25.0210
    5.0120
  -29.9810
  -40.0200
   14.9900
   10.0140

加權矩陣P
[[3 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 3 0]
 [0 0 0 0 0 6]]

法方程式 N矩陣
[[ 8 -2 -3]
 [-2 10 -6]
 [-3 -6 12]]

法方程式 U矩陣
   20.0690
    9.9020
  225.1140

未知數X
   25.0140
   30.0011
   40.0136

誤差矩陣V
   -0.0070
   -0.0249
   -0.0201
    0.0064
    0.0096
   -0.0016

單位權標準誤差：+/- 0.0295

未知數及精度分析
25.0140m +/- 0.0126 (m)
30.0011m +/- 0.0128 (m)
40.0136m +/- 0.0120 (m)

觀測量精度矩陣
    0.0126
    0.0128
    0.0128
    0.0120
    0.0120
    0.0102
